require('dotenv').config()


const PORT=process.env.PORT
const MONGOOSE_URL=process.env.MONGOOSE_URL
const JWT_SECRET_KEY=process.env.JWT_SECRET_KEY
const CLOUDINARY_CLOUD_NAME=process.env.CLOUDINARY_CLOUD_NAME
const CLOUDINARY_API_KEY=process.env.CLOUDINARY_API_KEY
const CLOUDINARY_API_SECRET=process.env.CLOUDINARY_API_SECRET


module.exports={
    PORT,
    MONGOOSE_URL,
    JWT_SECRET_KEY,
    CLOUDINARY_CLOUD_NAME,
    CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET
    
}